dist: trusty
install: true
language: java
jdk:
    - oraclejdk8

services:
    - xvfb

before_script:
    - cd ./mavendeps
    - mvn p2:site
    - mvn jetty:run &
    - sleep 10
    - cd ..

script: mvn clean verify
